# Generated by Django 3.2.8 on 2022-06-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220616_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='speciality',
            field=models.CharField(choices=[('Orthopedics', 'Orthopedics'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Internal Medicine', 'Internal Medicine')], max_length=100),
        ),
    ]
